services:
  sample-api:
    build: ./LK8sApi
    ports:
      - "5001:5001"
    networks:
      - lk8s-network
    
  sample-app:
    build: ./LK8sApp
    ports:
      - "5002:5002"
    networks:
      - lk8s-network

networks:
  app-network:
    driver: bridge
