services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - lk8s-network
  
  webdis:
    image: nicolas/webdis
    ports:
      - "7379:7379"
    depends_on:
      - redis
    networks:
      - lk8s-network

  lk8s-api:
    image: lk8s-api:${VERSION}
    ports:
      - "5001:5001"
    networks:
      - lk8s-network
    
  lk8s-app:
    image: lk8s-app:${VERSION}
    ports:
      - "5002:5002"
    networks:
      - lk8s-network

networks:
  lk8s-network:
    driver: bridge
